name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize] # Triggers on PR open and code updates

jobs:
  gemini_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai
          pip install google-generativeai tenacity

      - name: Get PR diff (Base64 Encode)
        id: get_diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          diff=$(git diff origin/${{ github.event.pull_request.base.ref }} HEAD)
          encoded_diff=$(echo "$diff" | base64)
          echo "$encoded_diff" > diff.b64 

      - name: Gemini API Call
        id: gemini_review_call
        run: |
          python <<EOF
          import os
          import google.generativeai as genai
          import base64
          from tenacity import retry, stop_after_attempt, wait_fixed
          import traceback
          import time

          genai.configure(api_key=os.environ['GEMINI_API_KEY'])
          model = genai.GenerativeModel('gemini-pro')

          @retry(stop=stop_after_attempt(3), wait=wait_fixed(5))
          def generate_review(prompt):
              print("Starting Gemini API call...")
              start_time = time.time()
              response = model.generate_content(prompt)
              end_time = time.time()
              print(f"Gemini API call completed in {end_time - start_time:.2f} seconds.")
              return response.text

          with open('diff.b64', 'r') as f:
              diff_base64 = f.read().strip()
          diff_decoded = base64.b64decode(diff_base64).decode('utf-8')
          prompt = f"Review this code diff for potential issues and provide feedback:\n\n{diff_decoded}"
          review_text = ""
          try:
              review_text = generate_review(prompt)
          except Exception as e:
              print(f"Error generating review: {e}")
              traceback.print_exc()
              review_text = f"An error occurred during Gemini review: {e}"

          escaped_review = review_text.replace('\n', '\\n') # Escape newlines

          print(f"REVIEW<<EOF") # Print the variable to stdout
          print(f"{escaped_review}\nEOF")

          EOF
          exit 0
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GRPC_GO_KEEP_ALIVE_TIMEOUT_MS: "60000"

      - name: Set Default Text
        id: default_text
        run: |
          echo "DEFAULT_TEXT=This is a default review comment." >> $GITHUB_OUTPUT
      
      - name: Post Default Review Comment
        if: steps.default_text.outputs.DEFAULT_TEXT!= ''
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "${{ steps.default_text.outputs.DEFAULT_TEXT }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Post Review Comment
        if: steps.gemini_review_call.outputs.REVIEW!= ''
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "$(echo "${{ steps.gemini_review_call.outputs.REVIEW }}" | sed 's/\\n/\n/g')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Empty review message
        if: steps.gemini_review_call.outputs.REVIEW == ''
        run: |
          echo "Gemini review was empty, no comment posted"
