name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gemini_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install google-generativeai requests PyGithub

      - name: Get PR diff
        id: diff
        run: |
          echo "DIFF<<EOF" >> $GITHUB_OUTPUT
          git diff origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Debug diff output
        run: echo "${{ steps.diff.outputs.DIFF }}"

      - name: Set DIFF environment variable
        run: echo "INPUT_DIFF=${{ steps.diff.outputs.DIFF }}" >> $GITHUB_ENV

      - name: Run Gemini review script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ./hack/gemini_review.py "${{ steps.diff.outputs.DIFF }}"