name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gemini_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai tenacity unidiff

      - name: Get PR diff (Base64 Encode)
        id: get_diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          diff=$(git diff origin/${{ github.event.pull_request.base.ref }} HEAD)
          encoded_diff=$(echo "$diff" | base64)
          echo "$encoded_diff" > diff.b64

      - name: Gemini API Call
        id: gemini_review_call
        run: |
          python <<EOF
          import os
          import google.generativeai as genai
          import base64
          from tenacity import retry, stop_after_attempt, wait_fixed
          import traceback
          import time
          from unidiff import PatchSet

          genai.configure(api_key=os.environ['GEMINI_API_KEY'])
          model = genai.GenerativeModel('gemini-pro')

          @retry(stop=stop_after_attempt(3), wait=wait_fixed(5))
          def generate_review(prompt):
              print("Starting Gemini API call...")
              start_time = time.time()
              response = model.generate_content(prompt)
              end_time = time.time()
              print(f"Gemini API call completed in {end_time - start_time:.2f} seconds.")
              return response.text

          with open('diff.b64', 'r') as f:
              diff_base64 = f.read().strip()
          diff_decoded = base64.b64decode(diff_base64).decode('utf-8')

          patch_set = PatchSet(diff_decoded)
          for patched_file in patch_set:
              for hunk in patched_file:
                  for line in hunk:
                      if line.is_added or line.is_removed or line.is_context:
                          prompt = f"Review this line of code for potential issues and provide feedback:\n\n```\n{line.line_no} {line.action} {line.value}\n```"
                          try:
                              review_text = generate_review(prompt)
                              # Use GitHub's API to post a comment on this specific line
                              os.system(f"gh pr review ${{ github.event.pull_request.number }} \
                                  --comment-at \"{patched_file.path}:{line.line_no}\" \
                                  --body \"{review_text}\"")
                          except Exception as e:
                              print(f"Error generating review: {e}")
                              traceback.print_exc()
                              # Consider logging the error or posting a general comment about the failure

          EOF
          exit 0
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRPC_GO_KEEP_ALIVE_TIMEOUT_MS: "600000"

      - name: Empty review message
        if: steps.gemini_review_call.outputs.REVIEW == ''
        run: |
          echo "Gemini review was empty, no comment posted"
