name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize] # Triggers on PR open and code updates

jobs:
  gemini_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Get PR diff (Base64 Encode)
        id: get_diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          diff=$(git diff origin/${{ github.event.pull_request.base.ref }} HEAD)
          encoded_diff=$(echo "$diff" | base64)
          echo "$encoded_diff" > diff.b64 

      - name: Gemini API Call
        id: gemini_review_call
        run: |
          python <<EOF
          import os
          import google.generativeai as genai
          import base64
          genai.configure(api_key=os.environ['GEMINI_API_KEY'])
          model = genai.GenerativeModel('gemini-pro')
          with open('diff.b64', 'r') as f:
              diff_base64 = f.read().strip()
          diff_decoded = base64.b64decode(diff_base64).decode('utf-8')
          prompt = f"Review this code diff for potential issues and provide feedback:\n\n{diff_decoded}"
          response = model.generate_content(prompt)
          print(f"REVIEW<<EOF")
          print(response.text)
          print(f"EOF")
          EOF
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Post Review Comment (Placeholder)
        run: |
          echo "This is a placeholder for posting a review comment."
          echo "Gemini Review: ${{ steps.gemini_review_call.outputs.REVIEW }}"
